name: Deploy Node-RED Flow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Demo deploy with scp
        run: |
          scp -o StrictHostKeyChecking=no flows.json settings.js \
          03541@localhost:/C/Users/03541/.node-red/


